---
title: "Analyze Census"
author: "Michael F. Nelson"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(data.table)
require(here)
require(ggplot2)
```



Calculate diversity indices:

```{r}
shannon = function(dat)
{
  dat1 = dat[which(dat > 0)]
  N = sum(dat1)
  pi = dat1/N
  log_pi = log(pi)
  pi_max = 1/length(pi)
  log_pi_max = log(pi_max)
  shan = -sum(log_pi * pi)
  shan_max = - length(pi) * pi_max * log_pi_max
  return(c(shannon = shan, max_shannon = shan_max, prop_shannon = shan / shan_max, n_extant = length(dat1)))
}

calc_div = function(dat)
{
  n_extant = apply(dat, 1, function(x) sum(x > 0))
  t(as.data.frame(apply(dat, 1, shannon)))
}

read_census = function(filename)
{
  dat = fread(filename)
  dat2 = dat[, -(1:2)]
  return(cbind(dat, calc_div(dat2)))
}

```



## Model Runner Command Line

./a.out ./cfg/cfg_100sp_0.txt 30000
./a.out ./cfg/cfg_100sp_1.txt 30000
./a.out ./cfg/cfg_100sp_2.txt 30000


./a.out ./cfg/cfg_100sp_3.txt 30000
./a.out ./cfg/cfg_100sp_4.txt 30000







## New Parameterization

```{r}
dat_100sp_0 = read_census(here("test", "out", "100_species_census0.txt"))
dat_100sp_1 = read_census(here("test", "out", "100_species_census1.txt"))
dat_100sp_2 = read_census(here("test", "out", "100_species_census2.txt"))
dat_100sp_3 = read_census(here("test", "out", "100_species_census3.txt"))
dat_100sp_4 = read_census(here("test", "out", "100_species_census4.txt"))

ggplot() +
  geom_line(aes(x = step, y = log(n_extant + 1)), data = dat_100sp_0) +
  geom_line(aes(x = step, y = log(n_extant + 1)), data = dat_100sp_1, col = 2) +
  geom_line(aes(x = step, y = log(n_extant + 1)), data = dat_100sp_2, col = 3) +
  geom_line(aes(x = step, y = log(n_extant + 1)), data = dat_100sp_3, col = 4) +
  geom_line(aes(x = step, y = log(n_extant + 1)), data = dat_100sp_4, col = 5)


ggplot() +
  geom_line(aes(x = step, y = prop_shannon), data = dat_100sp_0) +
  geom_line(aes(x = step, y = prop_shannon), data = dat_100sp_1, col = 2) +
  geom_line(aes(x = step, y = log(n_extant + 1)), data = dat_100sp_2, col = 3) +
  geom_line(aes(x = step, y = log(n_extant + 1)), data = dat_100sp_3, col = 4) +
  geom_line(aes(x = step, y = log(n_extant + 1)), data = dat_100sp_4, col = 5)


tail(dat_100sp_0)
tail(dat_100sp_1)
tail(dat_100sp_2)
tail(dat_100sp_3)
tail(dat_100sp_4)


ggplot() +
  geom_line(aes(x = step, y = prop_shannon), data = dat_100sp_1) +
  geom_line(aes(x = step, y = prop_shannon), data = dat_100sp_2, col = 2)



census_100sp_1$n_extant = apply(census_100sp_1, 1, function(x) sum(x > 0))
census_100sp_2$n_extant = apply(census_100sp_2, 1, function(x) sum(x > 0))

ggplot() +
  geom_line(aes(x = step, y = n_extant), data = census_100sp_1) +
  geom_line(aes(x = step, y = n_extant), data = census_100sp_2, col = 2)


```




```{r}
dat_5k1 = fread(here("model_runs", "out", "5k_species_census1.csv"), header = T)
dat_5k2 = fread(here("model_runs", "out", "5k_species_census2.csv"), header = T)
dat_5k3a = fread(here("model_runs", "out", "5k_species_census3a.csv"), header = T)
dat_5k3b = fread(here("model_runs", "out", "5k_species_census3b.csv"), header = T)



names(dat_5k1)[1] = "step"
names(dat_5k2)[1] = "step"


apply(dat_5k1[, -1], 1, function(x) sum(x > 0))
dat_5k1[, n_extant := apply(dat_5k1[, -1], 1, function(x) sum(x > 0))]
dat_5k2[, n_extant := apply(dat_5k2[, -1], 1, function(x) sum(x > 0))]
dat_5k3a[, n_extant := apply(dat_5k3a[, -1], 1, function(x) sum(x > 0))]
dat_5k3b[, n_extant := apply(dat_5k3b[, -1], 1, function(x) sum(x > 0))]

ggplot(dat_5k3b) +
  geom_line(aes(x = step, y = log(n_extant, 10))) +
  geom_line(aes(x = step, y = log(n_extant, 10)), data = dat_5k3a, col = 2) +
  geom_line(aes(x = step, y = log(n_extant, 10)), data = dat_5k1, col = 3) +
  geom_line(aes(x = step, y = log(n_extant, 10)), data = dat_5k2, col = 4)


ggplot() + geom_line(aes(x = step, y = log(n_extant, 10)), data = dat_5k1, col = 3) 


dat_5k1[, tail(n_extant)]
dat_5k2[, tail(n_extant)]
dat_5k3a[, tail(n_extant)]
dat_5k3b[, tail(n_extant)]

```
